// @ts-check

/**
 * Sidebar is auto-generated from the folder structure and frontmatter
 * (sidebar_position) of the markdown in ../btc-karma-gitbook, with category
 * labels/order coming from each folder's _category_.json.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
